name: Windows build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: setup vcpkg
      uses: lukka/get-vcpkg@v11

    - name: cache vcpkg
      uses: actions/cache@v4
      with:
        path: C:\Users\runneradmin\AppData\Local\vcpkg\archives
        key: windows-x86-vcpkg-freetype
        restore-keys: |
          windows-x86-vcpkg-freetype

    - name: install dependencies
      run: vcpkg install freetype --triplet x86-windows

    - name: cmake
      run: cmake -S . -B build -A Win32 -DCMAKE_TOOLCHAIN_FILE=$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake

    - name: build
      run: cmake --build build --config Release

    - name: test
      run: .\build\Release\unit_tests.exe

    - name: package
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path package
        Copy-Item build/Release/* package/
        Remove-Item package/unit_tests.exe
        Compress-Archive -Path package/* -DestinationPath fontbm.zip

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: fontbm
        path: fontbm.zip

    - name: release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: fontbm.zip
